### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 6209: invalid start byte

### ISSUE THREAD

**Issue by AlexSokokoliuk** [aurorayk/New_Hammer#41]
What should I do with that?
```
Traceback (most recent call last):
  File "pyhammer.py", line 864, in goToMain
    main(self.options)
  File "pyhammer.py", line 68, in main
    for i, line in enumerate(infile_init):
  File "C:\Users\alexs\Anaconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 6209: invalid start byte
```

**Comment by zephyr5050** [comment]
That looks like the input file you tried to load could not be read. Was your file corrupted in some way? Are you sure that it is a plain text file? `pyhammer.py` is reading the file and decoding it with a standard utf-8 decoder, but finding a byte that is not specified in utf-8.

If possible, can you post the input file you were using and describe the specific steps you followed to generate this exception? Either by describing your GUI interactions/inputs if you used the GUI or else your specific commands if you used the command line.

**Comment by sai-33** [comment]
![Screenshot (256)](https://user-images.githubusercontent.com/72378635/120895684-c2e3a100-c63b-11eb-92e1-ca5aa18d8f93.png)

UBUNTU
Python 3.9

**Comment by zephyr5050** [comment]
Neither `python pyhammer.py run` nor `python pyhammer.py install` are valid commands to be used when running PyHammer. Use either `python pyhammer.py -h` or view the [Starting PyHammer](https://github.com/BU-hammerTeam/PyHammer/wiki/Running-PyHammer#starting-pyhammer) for information on valid inputs when running PyHammer.

Admittedly, this error case should be caught and handled rather than having it error as it does.

**Comment by zephyr5050** [comment]
See #43 for another instance of this error being logged.

**Comment by sai-33** [comment]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 6209: invalid start byte 

How to solve this issue

**Comment by zephyr5050** [comment]
See my [previous comment](https://github.com/BU-hammerTeam/PyHammer/issues/41#issuecomment-855326523). If you still experience this issue after following the instructions therein, you can post additional information that would help address this issue.

**Comment by sai-33** [comment]
Yes, I am experiencing the same issue.
![Screenshot (258)](https://user-images.githubusercontent.com/72378635/121039660-e9861100-c7ce-11eb-9890-c5d7fbb3b1e8.png)

**Comment by zephyr5050** [comment]
It looks like you pulled up the GUI in your last attempt. Can you provide information everything you entered in each GUI as well as attach any input files you may have used which resulted in this error? Without seeing exactly how you're using this and what inputs you're providing, it will not be possible to troubleshoot.

This error looks to be an issue with the input file you've provided. Is this input file a standard text file?

**Comment by JunHuiLiu2017** [comment]
I also encountered the same issue. The data files I used are the `fits` and `txt` files provided in your `test_case`.

(pythonhammer) liujunhuideMacBook:PyHammer-2.0.0 liujunhui$ python pyhammer.py -g
qt.qpa.fonts: Populating font family aliases took 1018 ms. Replace uses of missing font family "Courier" with one that exists to avoid this cost. 
Traceback (most recent call last):
  File "/Users/liujunhui/PycharmProjects/PyHammer-2.0.0/pyhammer.py", line 864, in goToMain
    main(self.options)
  File "/Users/liujunhui/PycharmProjects/PyHammer-2.0.0/pyhammer.py", line 68, in main
    for i, line in enumerate(infile_init):
  File "/opt/miniconda3/envs/pythonhammer/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 6209: invalid start byte
Abort trap: 6
