### ISSUE TITLE
Error in runinng the test case via either gui or terminal.

### ISSUE THREAD

**Issue by spacefox-101** [aurorayk/New_Hammer#48]
When I run it through terminal I get the error. I have anaconda with all the updated modules as well.

FILE: test_case/spec-0618-52049-0372.fits
REASON: Could not guess spectral type. Error Message: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

And when I run it through the gui, I get this error.

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/ishaan/PyHammer-2.0.0/pyhammer.py", line 864, in goToMain
    main(self.options)
  File "/home/ishaan/PyHammer-2.0.0/pyhammer.py", line 68, in main
    for i, line in enumerate(infile_init):
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 6209: invalid start byte
Aborted (core dumped)

**Comment by mrobberto** [comment]
Same here, similar error:

  File "/PyHammer/PyHammer.py", line 68, in main
    for i, line in enumerate(infile_init):
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 6209: invalid start byte

**Comment by rlopezval** [comment]
Having the same error here. I could not run the test example, hopefully, someone help us to use this tool.
